name: Execute API tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  e2e-tests:
    runs-on: windows-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Execute UI Tests
      run: dotnet test ResolverTechTask\ResolverTechTask.csproj --settings AutomationFramework\Settings\app.runsettings
        
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4.0.0
      with:
        name: allure-results
        path: .\ResolverTechTask\bin\Debug\net8.0\allure-results
        if-no-files-found: error
        retention-days: 20
  
  report:
    needs: [e2e-tests]  
    runs-on: ubuntu-latest
  
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4.1.0
      with:
        name: allure-results
        path: ./allure-results
  
    - name: Get Allure history (optional)
      uses: actions/checkout@v4.1.1
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
  
    - name: Generate report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: allure-report
        allure_history: allure-history
        keep_reports: 20
  
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-report
